services:
  stream-backend:
    build:
      target: development
    image: stream-backend-development
    container_name: stream-backend-development
    ports:
      - "3001:3001"
      - "9228:9229"
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
    networks:
      - streams

networks:
  streams:
    driver: bridge
    name: streams
