services:
  stream-backend:
    extends:
      file: docker-compose.yaml
      service: stream-backend
    build:
      target: development
    image: stream-backend-test
    container_name: stream-backend-test
    command: npm run test
    volumes:
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
